import * as cheerio from "cheerio";
import esbuild from "esbuild";
import { minify } from "html-minifier-terser";
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

/* 
	Context: We use this script to bundle+minify all JS files generated by Astro (in `dist/_astro/`),
	then inline the resulting JS into `dist/index.html`, and finally minify the HTML. This results in a single 
	HTML file with no external dependencies, ideal for static hosting and reducing network calls for JS files.

	It may be that as this projects evolves, we want to split out some JS into separate files again or this interferes
	with functionality. When this day comes, we can remove this script and the `postbuild` step in package.json.
*/

const buildRoot = join(fileURLToPath(import.meta.url), "../../dist");
const paths = {
	html: join(buildRoot, "index.html"),
	js: join(buildRoot, "_astro"),
};

(async () => {
	const jsFiles = (await readdir(paths.js)).filter((f) => f.endsWith(".js"));

	console.log(`Bundling ${jsFiles.length} JS files from ${paths.js} ...`);

	const { outputFiles } = await esbuild.build({
		stdin: {
			contents: jsFiles.map((f) => `import "./${f}";`).join("\n"),
			resolveDir: paths.js,
		},
		bundle: true,
		format: "iife",
		platform: "browser",
		target: "es2020",
		minify: true,
		write: false, // Return as string instead of writing to disk
		legalComments: "none",
		drop: ["console", "debugger"],
		define: { "process.env.NODE_ENV": '"production"' },
		treeShaking: true,
		sourcemap: false,
		logLevel: "info",
	});

	console.log(`Deleting original JS files from ${paths.js} ...`);

	// Remove the original JS files and directory
	await rm(paths.js, { recursive: true, force: true });

	const html = await readFile(paths.html, "utf8");
	const $ = cheerio.load(html);

	console.log(`Inlining bundled JS into ${paths.html} ...`);
	// remove all <script src="..._astro..."> since they are now bundled and deleted
	$('script[src*="_astro"]').remove();
	$("head").append(`<script type="module">${outputFiles[0].text}</script>`);

	console.log(`Minifying ${paths.html} ...`);

	const minified = await minify($.html(), {
		collapseWhitespace: true,
		removeComments: true,
		minifyCSS: true,
		minifyJS: true,
		collapseBooleanAttributes: true,
		collapseInlineTagWhitespace: true,
		removeAttributeQuotes: true,
		removeRedundantAttributes: true,
		useShortDoctype: true,
		removeScriptTypeAttributes: true,
	});

	await writeFile(paths.html, minified);
	console.log(`✓ Bundled ${jsFiles.length} JS files → index.html`);
})();
