import * as cheerio from "cheerio";
import esbuild from "esbuild";
import { minify } from "html-minifier-terser";
import { readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/* 
	Context: We use this script to bundle+minify all JS files generated by Astro (in `dist/_astro/`),
	then inline the resulting single JS file into `dist/index.html`, and finally minify the HTML.
	This results in a single HTML file with no external dependencies, ideal for static hosting and preventing
	network calls for JS files.

	It may be that as this projects evolves, we want to split out some JS into separate files again or this interferes
	with functionality, but for now this is a good optimization. Once this day comes, we can remove this script and
	the `postbuild` step in package.json.
*/

const relativePath = "../dist/index.html";
const jsRelativePath = "../dist/_astro";
const bundleRelativePath = "../dist/bundle.js";

// Take all JS files in `jsRelativePath`, bundle+minify them into a single file at `bundleRelativePath`
async function bundleJs() {
	const __dirname = dirname(fileURLToPath(import.meta.url));
	const inDir = join(__dirname, jsRelativePath);
	const outFile = join(__dirname, bundleRelativePath);

	const js = (await readdir(inDir)).filter((f) => f.endsWith(".js"));
	if (!js.length) throw new Error("No .js files in " + inDir);

	// virtual entry that imports every file (preserves side effects)
	const entry = js.map((f) => `import "./${f}";`).join("\n");

	await esbuild.build({
		stdin: { contents: entry, resolveDir: inDir, sourcefile: "entry.js" },
		bundle: true, // follow imports + dedupe
		format: "iife",
		platform: "browser",
		target: ["es2017"],
		outfile: outFile,
		sourcemap: false,
		logLevel: "info",
		minify: true,
		legalComments: "none",
		define: { "process.env.NODE_ENV": '"production"' },
		drop: ["console", "debugger"],
		treeShaking: true,
	});

	await rm(inDir, { recursive: true, force: true });

	console.log(`Bundled ${js.length} files → ${outFile}`);
}

// Remove all old script tags referencing `_astro` files that we just bundled, then inline the bundled JS into the HTML
async function inlineJs() {
	const __dirname = dirname(fileURLToPath(import.meta.url));
	const file = join(__dirname, relativePath);

	const html = await readFile(file, "utf8");
	const $ = cheerio.load(html);

	// remove all <script src="..._astro...">
	$('script[src*="_astro"]').remove();

	const jsFile = join(__dirname, bundleRelativePath);
	const js = await readFile(jsFile, "utf8");
	$("head").append(`<script type="module">${js}</script>`);

	await writeFile(file, $.html());

	console.log(`Inlined JS into index.html`);
}

async function minifyHtml() {
	const __dirname = dirname(fileURLToPath(import.meta.url));
	const file = join(__dirname, relativePath);

	const before = (await stat(file)).size;
	const minified = await minify(await readFile(file, "utf8"), {
		collapseWhitespace: true,
		removeComments: true,
		minifyCSS: true,
		minifyJS: true,
		collapseBooleanAttributes: true,
		collapseInlineTagWhitespace: true,
		removeAttributeQuotes: true,
		removeRedundantAttributes: true,
		useShortDoctype: true,
		removeScriptTypeAttributes: true,
	});

	await writeFile(file, minified);

	const after = (await stat(file)).size;
	const saved = before - after;
	const percent = ((saved / before) * 100).toFixed(2);
	console.log(`Minified ${file}: ${before} → ${after} bytes (${saved} bytes - ${percent}% saved)`);
}

(async () => {
	await bundleJs();
	await inlineJs();
	await minifyHtml();
})();
